### ISSUE TITLE
undefined local variable or method `results'

### ISSUE THREAD

**Issue by tetsuo29** [ziadoz/bing-wallpaper-downloader#1]
Lubuntu 17.10
Ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

Command:
> ./bing-wallpaper-downloader.sh --destination=$HOME/Pictures/ --total=5

Images download but, the following error is thrown:

> ./bing-wallpaper-downloader.sh:12:in `<main>': undefined local variable or method `results' for main:Object (NameError)

**Comment by ziadoz** [comment]
@tetsuo29 Thanks, I've fixed this.
